target 'socketTest' do 
    platform :ios, '9.0'
    pod 'Masonry'
    pod 'AFNetworking','~>3.0'
    pod 'IQKeyboardManager'
    pod 'SDWebImage', '~> 3.8.2'
    pod 'CocoaAsyncSocket'
    pod 'SocketRocket'
end




